base:
- template:base-docker

provision:
  - mode: user
    script: |
      #!/bin/bash
      set -eux -o pipefail

      # Install uv
      curl -LsSf https://astral.sh/uv/install.sh | sh
      # Add uv to PATH for this script
      export PATH="$HOME/.local/bin:$PATH"
      # Install latest stable Python via uv
      uv python install

portForwards:
  - guestPortRange: [8000, 8030]
    hostPortRange: [8000, 8030]
