theme = "onedark"

[editor]
line-number = "relative"
mouse = false
clipboard-provider = "pasteboard"

default-yank-register = "+"
completion-timeout = 50

shell = ["zsh", "-c"]

[editor.indent-guides]
render = true
skip-levels = 1 

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal.space]
"." = "no_op"
E = "file_explorer_in_current_buffer_directory"

[keys.insert]
